package com.cwtms.entity.enums;

public enum TaskCategory {
    CLASSROOM_CLEANING,
    LABORATORY_CLEANING,
    RESTROOM_CLEANING,
    WASTE_COLLECTION,
    GARDEN_MAINTENANCE,
    ELECTRICAL_MAINTENANCE,
    PLUMBING_MAINTENANCE,
    WATER_TANK_INSPECTION,
    OTHER
}
